// povray generated by CHARMOL program
// convertxyzval 1.889726 

// basic settings
#include "transforms.inc"
background { color rgb <1.0, 1.0, 1.0> }
camera
 {
 location <0.000, 0.000, 47.592>
 look_at <0.0, 0.0, 0.0>
 angle 15
 right <-1.33, 0, 0>
 Axis_Rotate_Trans(<0.000, 0.000, 47.592>, -90.000)
 }
light_source { <0.000, 0.000, 47.592> color rgb <1, 1, 1> }
#declare BSAMBI = 0.200;
#declare BSDIFF = 0.800;
#declare BSSPEC = 0.800;

// atom 1
sphere
 {
 <      -0.127474,       0.000000,       0.000000>,       0.498888
 texture { pigment { rgb <  1.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
// halfbond 1 - 2
cylinder
 {
 <      -0.127474,       0.000000,       0.000000>, <       0.490461,      -0.821502,       0.000000>,       0.234326
 texture { pigment { rgb <  1.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
// halfbond 1 - 3
cylinder
 {
 <      -0.127474,       0.000000,       0.000000>, <       0.490461,       0.821502,       0.000000>,       0.234326
 texture { pigment { rgb <  1.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }

// atom 2
sphere
 {
 <       1.019792,      -1.525211,       0.000000>,       0.351489
 texture { pigment { rgb <  1.000  1.000  1.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
// halfbond 2 - 1
cylinder
 {
 <       1.019792,      -1.525211,       0.000000>, <       0.490461,      -0.821502,       0.000000>,       0.234326
 texture { pigment { rgb <  1.000  1.000  1.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }

// atom 3
sphere
 {
 <       1.019792,       1.525211,       0.000000>,       0.351489
 texture { pigment { rgb <  1.000  1.000  1.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
// halfbond 3 - 1
cylinder
 {
 <       1.019792,       1.525211,       0.000000>, <       0.490461,       0.821502,       0.000000>,       0.234326
 texture { pigment { rgb <  1.000  1.000  1.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }

// gauge 2 - 3
cylinder
 {
 <       1.019792,      -1.137299,       0.000000>, <       1.019792,      -0.870167,       0.000000>,       0.044522
 texture { pigment { rgb <  0.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
sphere
 {
 <       1.019792,      -0.752800,       0.000000>,       0.044522
 texture { pigment { rgb <  0.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
cylinder
 {
 <       1.019792,      -0.635432,       0.000000>, <       1.019792,      -0.368301,       0.000000>,       0.044522
 texture { pigment { rgb <  0.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
sphere
 {
 <       1.019792,      -0.250933,       0.000000>,       0.044522
 texture { pigment { rgb <  0.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
cylinder
 {
 <       1.019792,      -0.133566,       0.000000>, <       1.019792,       0.133566,       0.000000>,       0.044522
 texture { pigment { rgb <  0.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
sphere
 {
 <       1.019792,       0.250933,       0.000000>,       0.044522
 texture { pigment { rgb <  0.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
cylinder
 {
 <       1.019792,       0.368301,       0.000000>, <       1.019792,       0.635432,       0.000000>,       0.044522
 texture { pigment { rgb <  0.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
sphere
 {
 <       1.019792,       0.752800,       0.000000>,       0.044522
 texture { pigment { rgb <  0.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
cylinder
 {
 <       1.019792,       0.870167,       0.000000>, <       1.019792,       1.137299,       0.000000>,       0.044522
 texture { pigment { rgb <  0.000  0.000  0.000> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }

// arrow
cylinder
 {
 <       1.019792,      -1.525211,       0.000000>, <      -0.808444,      -2.744034,       0.000000>,       0.093730
 texture { pigment { rgb <  0.800  0.600  0.200> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
cone
 {
 <      -0.808444,      -2.744034,       0.000000>,       0.187461, <      -0.964421,      -2.848019,       0.000000>,       0.000000
 texture { pigment { rgb <  0.800  0.600  0.200> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }

// arrow
cylinder
 {
 <       1.019792,       1.525211,       0.000000>, <      -0.808444,       2.744034,       0.000000>,       0.093730
 texture { pigment { rgb <  0.800  0.600  0.200> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }
cone
 {
 <      -0.808444,       2.744034,       0.000000>,       0.187461, <      -0.964421,       2.848019,       0.000000>,       0.000000
 texture { pigment { rgb <  0.800  0.600  0.200> } finish { ambient BSAMBI diffuse BSDIFF specular BSSPEC } }
 }

